version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "0.0.0.0:3001:3001"
    volumes:
      - "/app/node_modules"
      - "/app/.next"
      - ".:/app"

networks:
  default:
    external:
      name: smart_cities_guide_networks
